name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - run: |
        python -m pip install --upgrade pip
        pip install playwright nest_asyncio aiohttp tenacity

    - run: |
        python -m playwright install --with-deps

    - run: |
        python gorkv3.py || echo "Script failed, but continuing to capture output"
        ls -l output_*.json || echo "No output files found"

    - run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        OUTPUT_FILE=$(ls -t output_*.json 2>/dev/null | head -n 1 || echo "")
        if [ -n "$OUTPUT_FILE" ]; then
          mv "$OUTPUT_FILE" output.json
          git add output.json
          git commit -m "Add latest output.json from scrape job"
          git push
        else
          echo "No output file generated, skipping commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}